l_korean:
 DIVISION_QUEUED:0 "$N$개 분대"
 DIVISIONS_QUEUED:0 "$N$개 분대"
 DEPLOYMENT_DIVISION_LABEL:0 "분대"
 DEPLOYMENT_TEMPLATE_ITEM_EDIT:0 "§G클릭하여 분대 템플릿 편집§!"
 DEPLOYMENT_TEMPLATE_ITEM_VIEW:0 "§G클릭하여 분대 템플릿 보기§!"
 DEPLOYMENT_DESIGNER:0 "분대 디자이너"
 DEPLOYMENT_REMOVE_DIVISION:0 "분대 취소"
 DEPLOYMENT_DEPLOYMENT_LABEL:0 "모집 및 배치"
 DEPLOYMENT_NOT_ALLOWED_REASON_EXCEED_DIVISION_CAP:0 "§R배치§!할 수 없습니다. 해당 부대가 분대 템플릿 한도를 초과합니다."
 HAS_ARMIES_WITH_TEMPLATE:0 "§R현재 $AMOUNT|H$개의 분대가 이 템플릿을 사용하고 있어 삭제할 수 없습니다.§!"
 HAS_ARMIES_WITH_OLD_TEMPLATE:0 "§R현재 $AMOUNT|H$개의 분대가 이 템플릿에서 새 템플릿으로 전환 중이므로 삭제할 수 없습니다(새 템플릿 장비 수령 대기 중).§!"
 CONVEYOR_TEMPLATE_ICON_DESC:0 "이 배치는 $TEMPLATE|H$ 템플릿을 사용하는 분대들을 생성합니다."
 CONVEYOR_SERIES_INCREASE_DESC:0 "각 생산 라인이 완료할 분대 연쇄 훈련 횟수를 늘립니다.\n\n무한으로 설정하면 이전 분대가 배치될 때마다 새로운 분대를 훈련합니다."
 CONVEYOR_SERIES_AMOUNT_DESC:0 "생산 라인이 제거되기 전까지 훈련할 분대의 수입니다.\n\n무한으로 설정하면 이전 분대가 배치될 때마다 새로운 분대를 훈련합니다."
 CONVEYOR_SERIES_DECREASE_DESC:0 "각 생산 라인이 완료할 분대 연쇄 훈련 횟수를 줄입니다.\n\n무한으로 설정하면 이전 분대가 배치될 때마다 새로운 분대를 훈련합니다."
 CONVEYOR_CAN_NOT_TRAIN_COUNT:1 "§R인력이나 장비가 부족하여 $DIVS|H$개의 분대를 훈련할 수 없습니다.§!"
 EXCEEDING_DIVISION_CAP:0 "§R분대 템플릿 한도 초과§!"
 DEPLOYMENT_CANNOT_TRAIN_SPECIAL_UNITS:1 "새로운 특수 템플릿 분대를 훈련할 수 없습니다."
 DEPLOYMENT_EXILE_WITH_NO_CAPITAL:0 "§H망명 정부§! 상태에서는 새로운 분대를 훈련하기 위해 실효 지배 중인 §H수도§!가 필요합니다."
 CANT_CHANGE_DUE_TO_SPECIAL_FORCES_CAP:0 "특수부대 한도를 초과하게 되므로 이 템플릿으로 변경할 수 없습니다."
 CANT_CHANGE_DUE_TO_DIVISION_CAP:0 "분대 한도를 초과하게 되므로 이 템플릿으로 변경할 수 없습니다."
 SPECIAL_FORCES_CAP_LIMIT_DESC:0 "이 분대는 특수부대 한도의 제한을 받습니다(가장 낮은 한도임)."
 DIVISION_CAP_OF_TEMPLATE:0 "이 템플릿의 보유 한도는 $NUM|Y$개입니다."
 DIVISION_CAP_USAGE_DESC:0 "현재 $NAME|Y$ 분대를 $USED|Y$개 운용 중이며 $IN_TRAINING|Y$개를 훈련 중입니다(최대 허용: $CAP|Y$개)."
 DIVISION_CAP_LIMIT_DESC:0 "이 분대는 템플릿 한도의 제한을 받습니다(가장 낮은 한도임)."
 DEPLOYMENT_MAX_DEPLOYABLE_DIVISION_FOR_TEMPLATE:0 "이 템플릿을 사용하는 분대를 최대 $TRAINABLE|Y$개 더 추가할 수 있습니다."
